/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.Ltp3.Apresentacao;

/**
 *
 * @author anderson
 */
public class frmListarUsuariosSistema extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmListarUsuariosSistema
     */
    public frmListarUsuariosSistema() {
        initComponents();
        lblDataDe.setVisible(false);
        lblNome.setVisible(false);
        btnFiltrar.setVisible(false);
        txtFiltro.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuariosSistema = new javax.swing.JTable();
        lblFiltro = new javax.swing.JLabel();
        cbxFiltro = new javax.swing.JComboBox();
        txtFiltro = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblDataDe = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Listagem dos Usuarios de Sistema");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));

        tblUsuariosSistema.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Cpf", "Data Nascimento"
            }
        ));
        jScrollPane1.setViewportView(tblUsuariosSistema);

        lblFiltro.setText("Filtro:");

        cbxFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Nome", "Cpf", "Idade" }));
        cbxFiltro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxFiltroItemStateChanged(evt);
            }
        });

        btnFiltrar.setText("Filtrar");

        lblNome.setText("Nome;");

        lblDataDe.setText("Data de :");
        lblDataDe.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFiltro)
                        .addGap(31, 31, 31)
                        .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDataDe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome)
                        .addGap(34, 34, 34)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFiltro)
                    .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrar)
                    .addComponent(lblNome)
                    .addComponent(lblDataDe))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxFiltroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxFiltroItemStateChanged
        /*JOptionPane.showMessageDialog(rootPane,"ssdfs");
        lblFiltro.setVisible(false);*/

        if(cbxFiltro.getSelectedItem().equals("Selecione")){
            lblNome.setVisible(false);
            txtFiltro.setVisible(false);
            btnFiltrar.setVisible(false);
            lblDataDe.setVisible(false);

        }else if(cbxFiltro.getSelectedItem().equals("Nome")){
            lblNome.setText("Nome:");
            lblNome.setVisible(true);
            txtFiltro.setVisible(true);
            btnFiltrar.setVisible(true);
            lblDataDe.setVisible(false);

        }else if(cbxFiltro.getSelectedItem().equals("Idade")){
            lblNome.setText("Idade:");
            lblNome.setVisible(true);
            txtFiltro.setVisible(true);
            btnFiltrar.setVisible(true);
            lblDataDe.setVisible(false);
        }else if(cbxFiltro.getSelectedItem().equals("CPF:")){
            lblNome.setText("CPF:");
            lblNome.setVisible(true);
            txtFiltro.setVisible(true);
            btnFiltrar.setVisible(true);
            lblDataDe.setVisible(false);
        }
        
    }//GEN-LAST:event_cbxFiltroItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox cbxFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataDe;
    private javax.swing.JLabel lblFiltro;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tblUsuariosSistema;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
