/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.Ltp3.Apresentacao;

import com.birosoft.liquid.LiquidLookAndFeel;
import javax.swing.UIManager;


/**
 *
 * @author anderson
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MenuSuperior = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuNovo = new javax.swing.JMenu();
        MenuItemUsuario = new javax.swing.JMenuItem();
        MenuItemCliente = new javax.swing.JMenuItem();
        MenuItemProduto = new javax.swing.JMenuItem();
        MenuItemTipoPagamento = new javax.swing.JMenuItem();
        MenuItemSair = new javax.swing.JMenuItem();
        MenuUsuarios = new javax.swing.JMenu();
        MenuItemListarUsuarios = new javax.swing.JMenuItem();
        MenuVendas = new javax.swing.JMenu();
        MenuItemNovaVanda = new javax.swing.JMenuItem();
        MenuItemHistorico = new javax.swing.JMenuItem();
        MenuClientes = new javax.swing.JMenu();
        MenuItemListarClientes = new javax.swing.JMenuItem();
        MenuTiposPagamento = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Vendas");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jMenu1.setText("Sistema");

        MenuNovo.setText("Novo");

        MenuItemUsuario.setText("Usuário");
        MenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUsuarioActionPerformed(evt);
            }
        });
        MenuNovo.add(MenuItemUsuario);

        MenuItemCliente.setText("Cliente");
        MenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemClienteActionPerformed(evt);
            }
        });
        MenuNovo.add(MenuItemCliente);

        MenuItemProduto.setText("Produto");
        MenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemProdutoActionPerformed(evt);
            }
        });
        MenuNovo.add(MenuItemProduto);

        MenuItemTipoPagamento.setText("Tipo de Pagamento");
        MenuItemTipoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemTipoPagamentoActionPerformed(evt);
            }
        });
        MenuNovo.add(MenuItemTipoPagamento);

        jMenu1.add(MenuNovo);

        MenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        MenuItemSair.setText("Sair");
        MenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemSair);

        MenuSuperior.add(jMenu1);

        MenuUsuarios.setText("Usuários");

        MenuItemListarUsuarios.setText("Listar");
        MenuItemListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemListarUsuariosActionPerformed(evt);
            }
        });
        MenuUsuarios.add(MenuItemListarUsuarios);

        MenuSuperior.add(MenuUsuarios);

        MenuVendas.setText("Vendas");

        MenuItemNovaVanda.setText("Nova");
        MenuItemNovaVanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemNovaVandaActionPerformed(evt);
            }
        });
        MenuVendas.add(MenuItemNovaVanda);

        MenuItemHistorico.setText("Histórico");
        MenuItemHistorico.setMaximumSize(new java.awt.Dimension(820, 620));
        MenuItemHistorico.setMinimumSize(new java.awt.Dimension(820, 820));
        MenuItemHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemHistoricoActionPerformed(evt);
            }
        });
        MenuVendas.add(MenuItemHistorico);

        MenuSuperior.add(MenuVendas);

        MenuClientes.setText("Clientes");

        MenuItemListarClientes.setText("Listar");
        MenuClientes.add(MenuItemListarClientes);

        MenuSuperior.add(MenuClientes);

        MenuTiposPagamento.setText("Tipos de Pagamento");

        jMenuItem1.setText("Listar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuTiposPagamento.add(jMenuItem1);

        MenuSuperior.add(MenuTiposPagamento);

        setJMenuBar(MenuSuperior);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_MenuItemSairActionPerformed

    private void MenuItemTipoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemTipoPagamentoActionPerformed
        frmCadastroFormasPagamento janela = new frmCadastroFormasPagamento();
        janela.setVisible(true);
        add(janela);
    }//GEN-LAST:event_MenuItemTipoPagamentoActionPerformed

    private void MenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemProdutoActionPerformed
       frmCadastroProduto janela = new frmCadastroProduto();
       janela.setVisible(true);
       add(janela);
    }//GEN-LAST:event_MenuItemProdutoActionPerformed

    private void MenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUsuarioActionPerformed
        frmCadastroUsuarioSistema janela = new frmCadastroUsuarioSistema();
        janela.setVisible(true);
        add(janela);
    }//GEN-LAST:event_MenuItemUsuarioActionPerformed

    private void MenuItemHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemHistoricoActionPerformed
        frmListarVendas janela = new frmListarVendas();
        janela.setVisible(true);
        add(janela);
    }//GEN-LAST:event_MenuItemHistoricoActionPerformed

    private void MenuItemListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemListarUsuariosActionPerformed
        frmListarUsuariosSistema janela = new frmListarUsuariosSistema();
        janela.setVisible(true);
        add(janela);
    }//GEN-LAST:event_MenuItemListarUsuariosActionPerformed

    private void MenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemClienteActionPerformed
        frmCadastroCliente janela = new frmCadastroCliente();
        janela.setVisible(true);
        add(janela);
    }//GEN-LAST:event_MenuItemClienteActionPerformed

    private void MenuItemNovaVandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemNovaVandaActionPerformed
        frmVenda janela = new frmVenda();
        janela.setVisible(true);
        add(janela);
    }//GEN-LAST:event_MenuItemNovaVandaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        frmListarTipoPagamento janela = new frmListarTipoPagamento();
        janela.setVisible(true);
        add(janela);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
           System.setProperty(
          "Quaqua.tabLayoutPolicy","wrap"
         );
         
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                 
                }
                
        /*        UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
                LiquidLookAndFeel.setLiquidDecorations(true, "liquid");
                * 
        * */
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenuItem MenuItemCliente;
    private javax.swing.JMenuItem MenuItemHistorico;
    private javax.swing.JMenuItem MenuItemListarClientes;
    private javax.swing.JMenuItem MenuItemListarUsuarios;
    private javax.swing.JMenuItem MenuItemNovaVanda;
    private javax.swing.JMenuItem MenuItemProduto;
    private javax.swing.JMenuItem MenuItemSair;
    private javax.swing.JMenuItem MenuItemTipoPagamento;
    private javax.swing.JMenuItem MenuItemUsuario;
    private javax.swing.JMenu MenuNovo;
    private javax.swing.JMenuBar MenuSuperior;
    private javax.swing.JMenu MenuTiposPagamento;
    private javax.swing.JMenu MenuUsuarios;
    private javax.swing.JMenu MenuVendas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
